#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


mkdir -p logs
python ./manage.py collectstatic --noinput
python ./manage.py migrate
exec /usr/local/bin/gunicorn config.wsgi --workers=3 --bind 0.0.0.0:5000 \
  --chdir=/app/camerator --access-logfile gunicorn_access.log \
  --name gunicorn_camerator --capture-output
