# Generated by Django 4.2 on 2025-01-15 12:02

from django.db import migrations, models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, blank=True, max_length=255),
                ),
                ("description", models.TextField()),
                ("number_of_photos", models.IntegerField(default=10)),
                ("thumbnail", models.ImageField(upload_to="services/images/")),
                (
                    "processing",
                    models.CharField(
                        choices=[("retouch", "Retouch"), ("finished", "Finished")],
                        default="retouch",
                        verbose_name="Processing type",
                    ),
                ),
                (
                    "camera",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("semi professional", "Semi-Professional"),
                            ("newbie", "Newbie"),
                        ],
                        default="semi professional",
                        verbose_name="Camera type",
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("12MP", "12MP"),
                            ("108MP", "108MP"),
                            ("256MP", "256MP"),
                        ],
                        default="12MP",
                        verbose_name="Resolution",
                    ),
                ),
                ("term", models.IntegerField(default=7)),
                ("price", models.IntegerField(default=10)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("published", "Published"), ("draft", "Draft")],
                        default="published",
                        verbose_name="Status",
                    ),
                ),
            ],
        ),
    ]
